### ISSUE TITLE
请问Nacos-sync 高可用集群设计吗？

### ISSUE THREAD

**Issue by chenzhenchang** [nacos-group/nacos-sync#103]
用于过度ZK到nacos 服务迁移，感谢您的回答，谢谢！

**Comment by paderlol** [comment]
这个可以参考官方文档 [设计文档](https://nacos.io/zh-cn/docs/nacos-sync.html),Nacos Sync由于使用了数据库存储同步任务信息,所以可以使用多个Nacos sync实例共享同一个数据库进行同步,来达到集群的效果
