### ISSUE TITLE
nacos-sync使用nacos-client 1.1.3版本后,nacos数据无法同步到ZK

### ISSUE THREAD

**Issue by brucelwl** [nacos-group/nacos-sync#104]
我看了下nacos-sync的nacos客户端版本使用的是0.5.0, 
由于我的``nacos-server端版本是1.1.3``
当我将nacos-sync中的依赖换成``nacos-client 1.1.3``版本后,
nacos数据向ZK同步无效的,

**Comment by paderlol** [comment]
目前已经升级到1.1.3,也没有同步zk的不生效问题,不过如果你是想从nacos同步到spring cloud zk那就不行了
