### ISSUE TITLE
如何  nacos-sync  将 naocs 0.8 升级到 nacos  1.1.3

### ISSUE THREAD

**Issue by Seriels** [nacos-group/nacos-sync#111]
我现在遇到了  低版本的nacos 向高级版本的naocs 升级 发现无法  同步

**Comment by paderlol** [comment]
具体问题是指？

**Comment by Seriels** [comment]
我按照文档 启动并且配置好 nacos-sync  并开启了 0.8 （172.18.0.2）到 1.1.3（172.19.0.4）  的 同步   但是 日志却只有提示一句 从数据库中查询到一个同步任务，发出一个同步事件  然后什么都没有发生了。。。。  1.1.3 的nacos 里面还是什么都没有。。。 所以 如何在生产环境平滑升级到 1.1.3
![image](https://user-images.githubusercontent.com/33693501/68260014-83775c00-0076-11ea-8ec6-61cb3115cdc0.png)
![image](https://user-images.githubusercontent.com/33693501/68260023-912ce180-0076-11ea-985e-28d7dfa7613c.png)

**Comment by paderlol** [comment]
如果是0 8到1.1.3应该是版本不兼容，api发生变化了

**Comment by Seriels** [comment]
所以  我该如何使nacos升级   , nacos-sync  什么时候会支持 这种低版本向升级到高版本的 功能 TAT

**Comment by paderlol** [comment]
1.0以后的版本都是稳定的，而且1.0以后有了导出

**Comment by paderlol** [comment]
你的这个问题我反馈给nacos这边了，会考虑下怎么处理这个兼容问题

**Comment by Seriels** [comment]
好的 谢谢 了 麻烦您了
