### ISSUE TITLE
nacos-sync 对 dubbo http协议的支持

### ISSUE THREAD

**Issue by sanguolingzi** [nacos-group/nacos-sync#112]
环境:
使用的是dubbo2.7.1  zookeeper 3.4.13 dubbo使用的是 http协议注册到zk   并配置使用servelt接收方式接收请求。
nacos-sync.0.3.2     nacos.1.1.4  版本 
使用nacos-sync 连接 zk和nacos进行同步  

现象:
消费端连接nacos 消费
出现服务无法消费的情况 http请求的uri上 没有dubbo对应的interface 导致 dubbo服务端无法解析 

其它情况:
使用dubbo协议注册到zk 没有这个问题

**Comment by paderlol** [comment]
你的需求是？

**Comment by sanguolingzi** [comment]
dubbo注册zk  通过 nacos-async 同步到 nacos-server  消费端通过nacos-server消费
dubbo的底层使用http协议

**Comment by sanguolingzi** [comment]
同样的搭配方式下,只是协议dubbo底层使用的 dubbo协议  就可以调用

**Comment by sanguolingzi** [comment]
![服务信息说明](https://user-images.githubusercontent.com/15864564/68646254-9944bf80-0555-11ea-8bc1-2c233761763f.png)
这个图是我使用http协议后 在nacos中查看的服务信息
图片中左侧的是直接使用nacos 
图片中右侧是经过nacos-async 从zk中同步到nacos
可以看到左右两个服务的信息有一些差异
主要是path=dubbo/demoApi 这一项在右侧不存在
不知道是不是导致使用http协议无法调用的原因

**Comment by paderlol** [comment]
我知道了，目前sync默认使用的dubbo协议

**Comment by sanguolingzi** [comment]
好的,那这一块后续是否会更新支持更多的协议?

**Comment by paderlol** [comment]
会的，或者你们也可以贡献pr进来一起做的

**Comment by sanguolingzi** [comment]
那请问下这一块相关的代码说明有么?

**Comment by paderlol** [comment]
官网有一点介绍的
