### ISSUE TITLE
内存溢出 请升级 nacos.client version到 1.1.4

### ISSUE THREAD

**Issue by xiongrl** [nacos-group/nacos-sync#113]
nacos client在多次 registerInstance 后，导致心跳的定时任务越来越多，导致内存溢出
详见 https://github.com/alibaba/nacos/blob/1.1.4/client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java#L61

下面是dump分析
![image](https://user-images.githubusercontent.com/4568603/69933115-8f84fb00-1508-11ea-85e6-f6315193ba16.png)

**Comment by paderlol** [comment]
我周末会进行升级

**Comment by paderlol** [comment]
Fixed 请升级到0.3.3版本
