### ISSUE TITLE
Eureka同步到nacos，eureka下线，nacos不下线

### ISSUE THREAD

**Issue by niejian** [nacos-group/nacos-sync#124]
Eureka同步到nacos时，当某个服务下线，Eureka上已找不到这个服务信息。但是在nacos界面上还能看到。查看access_log仍然有心跳服务请求。

**Comment by paderlol** [comment]
谢谢，这确实是一个问题，我马上修复下

**Comment by paderlol** [comment]
已经修复掉了,等下会发一个小版本上去.

**Comment by niejian** [comment]
> 谢谢，这确实是一个问题，我马上修复下

在不能修改eureka-server的情况下，我这边加了个定时器去扫描task表，判断是否还在Eureka中，不过不在的话就调用nacosSync  <font color=red>**下线**</font> 按钮的http请求。这样也能做到nacos对eureka的同步

**Comment by paderlol** [comment]
可以使用新的版本，我已经修复了

**Comment by niejian** [comment]
> 可以使用新的版本，我已经修复了

是master分支吗，兄弟

**Comment by niejian** [comment]
> 可以使用新的版本，我已经修复了
大胸弟威武。升级到0.3.4就解决了
