### ISSUE TITLE
zk同步过来的服务会掉线

### ISSUE THREAD

**Issue by niejian** [nacos-group/nacos-sync#129]
zk同步过来的服务在一段时间后会在nacos控制台消失，但是dubbo-monitor上依然存在该服务

**Comment by paderlol** [comment]
如果zk发生移除,确实会马上消失,另外一种是心跳导致的,这个要具体看才知道,我测试了下没有重现这个问题

**Comment by niejian** [comment]
> 如果zk发生移除,确实会马上消失,另外一种是心跳导致的,这个要具体看才知道,我测试了下没有重现这个问题

没有重连机制吗。服务可能重启。但是重启后，nacosSync似乎没有重连。

**Comment by paderlol** [comment]
哪边的服务重启？是指nacos吗？

**Comment by niejian** [comment]
> 哪边的服务重启？是指nacos吗？

不是nacos；是同步过来的服务，xxxService。<br/>
nacosSync这边重连应该是要以task表中的数据跟zk上的znode节点做对比吧，

**Comment by paderlol** [comment]
你重启的话只要zk节点有变化，这边就会重新同步，你重启服务下线，就会移除，重新上线，zk变化就会同步到nacos

**Comment by niejian** [comment]
> ，这边就会重新同步，你重启服务下线，就会移除，重新上线，zk变化就会同步到nacos

是的，我这边测试过几次，znode这边的变化能比较快速的反馈到nacos。但是我提的 注册到zk上的服务重启，导致nacos上对应的服务信息消失也确实存在。

**Comment by paderlol** [comment]
好，我晚上测一下， dubbo的版本是？

**Comment by niejian** [comment]
> 好，我晚上测一下， dubbo的版本是？

比较老的项目。dubbox （2.8.4）

**Comment by paderlol** [comment]
Ok，我测下，如果确实有这个问题，我看能否马上修复下

**Comment by paderlol** [comment]
我刚刚测试了 dubbox 2.8.4 试验了重启和停止后重启两个场景,同步都是正常的,
Nacos : 1.1.4
Sync:0.3.4
Maven依赖:
``` xml
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.8.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.4.6</version>
        </dependency>
        <dependency>
            <groupId>com.github.sgroschupf</groupId>
            <artifactId>zkclient</artifactId>
            <version>0.1</version>
        </dependency>
```
![image](https://user-images.githubusercontent.com/7919984/72164726-32327280-3401-11ea-9614-2c16cdefb5fb.png)
你可能要排查下你自己的程序了,不排除是使用过低的zk server导致的,我这里使用的是3.4.9
