### ISSUE TITLE
新功能:同步ZK数据同步到Nacos

### ISSUE THREAD

**Issue by wyp12** [nacos-group/nacos-sync#13]
## 背景
Dubbo在2.6.5版本支持了Nacos作为其服务发现框架,也就是,以后Dubbo用户,可以使用Nacos了,问题来了,Dubbo支持ZK作为其服务发现框架,并且占很大一部分比例,(Dubbo+zk)的存量用户想迁移到Dubbo+Nacos的模式,如何支持呢?

## 方案1:客户端全量升级
暴力模式,全量停机,把Provider和Consumer全部重新升级至Dubbo2.6.5版本,此方式适用于可接受停机的产品业务
### 优点
是不需要引入其他中心系统,
简单
### 缺点
有业务方场景限制

## 方案2:客户端全量升级+切流
统一接入层引流,这个要求业务系统的基础设置要比较完善,在统一接入层能够将流量切走,同时成本也比较大,需要一样规模的同一个集群进行切换升级,这个类似蓝绿发布,相比方案1,增加了切流及的操作,来达到业务不停机的目的
![image](https://user-images.githubusercontent.com/4252147/50347965-6cb93b00-0572-11e9-8acd-aa122c049c1a.png)

## 缺点
有业务方场景限制

## 方案3:客户端支持(多发布+多订阅)
Dubbo客户端支持多发布,多订阅模式,即Provider可以将自己的地址发布到Zk集群的同时,又发布到Nacos集群,Consumer订阅时,可以订阅Zk集群的服务地址同时也能订阅到Nacos集群的服务地址
![image](https://user-images.githubusercontent.com/4252147/50348001-878baf80-0572-11e9-93aa-fd1c48b7dc6f.png)

## 优点
不需要引入其他中心系统
## 缺点
Dubbo客户端改动量大
客户端的可控性不在手上,难以推动快速落地
客户端有升级顺序限制(先升Provider,会导致老的Consumer调用不到,产生容量问题)

## 迁移步骤:
1、新搭建一个Nacos集群
2、必须先升级Dubbo Consumer客户端,可以订阅到2端集群的数据,并且聚合使用(这里不会出现负载不均的情况)
2、再Dubbo Provider升级客户端,此时Nacos集群中,Zk集群中,都有该Provider地址
4、关闭原ZK集群,升级完毕

## 方案4:NacosSync双向同步

> 注:“新”的意思是升级了Dubbo2.6.5连接到Naocs注册中心的客户端

​ | 新Dubbo Provider | 老Dubbo Provider
-- | -- | --
新Dubbo Consumer | 支持 | 支持
老Dubbo Consumer | 支持 | 支持

## 优点
相比方案3,改动点都在NacosSync,可控

## 缺点
Nacos目前还不支持Nacos同步到zk,目前已经在做的开发计划支持zk同步到Nacos
双向同步功能支持时,需要对服务进行打标,避免循环同步,但是需要ZK能支持服务打标功能?目前没有
NacosSync的高可用模式下,不支持双向同步,高可用模式是指NaocsSync集群部署,原因是目前NacosSync同步到目标集群,是多台NacosSync重复同步,需要目标集群支持去重功能

## 迁移步骤
新搭建一个Nacos集群
新搭建一个NacosSync集群
升级老客户端到新客户端(Provider和Consumer无顺序升级要求)
升级完毕,关闭zk集群,关闭NacosSync集群

## 方案5:NacosSync单向同步

​ | 新Dubbo Provider | 老Dubbo Provider
-- | -- | --
新Dubbo Consumer | 支持 | 支持
老Dubbo Consumer | 不支持 | 支持

最大问题是:没办法支持老的Dubbo Consumer订阅新的Dubbo Provider!

若无法解决这个问题,可操作性也没有!除非增加机器成本,即新Provider用新机器,这样老的DubboConsumer就不会因为容量问题出现风险

## 迁移步骤
1、 搭建Nacos集群
2、 搭建NacosSync集群
3、新申请Provider机器,连接到Nacos集群
4、老的Consumer升级到新版本Consumer
5、老的Provider升级到新版本Provider
6、升级完毕,关闭zk集群,关闭NacosSync集群

![image](https://user-images.githubusercontent.com/4252147/50348267-38924a00-0573-11e9-8e17-e4d473684943.png)

​ | 新Dubbo Provider | 老Dubbo Provider
-- | -- | --
新Dubbo Consumer | 支持 | 支持
老Dubbo Consumer | 支持 | 支持

## 缺点
需要推动Dubbo Provider支持多发布功能

## 迁移步骤
1、搭建Nacos集群
2、搭建NacosSync集群
3、升级老的Provider到多发布版本
4、老的Consumer升级到新版本Consumer
5、升级完毕,关闭zk集群,关闭NacosSync集群

## 方案选型

> 注:高=3,中=2,低=1

​ | 开发成本 | 机器成本 | 风险成本 | 用户成本 | 维护成本 | 推动成本 | 场景限制 | 成本分
-- | -- | -- | -- | -- | -- | -- | -- | --
方案1 | 1 | 1 | 3 | 1 | 1 | 1 | 有 | 8
方案2 | 1 | 1 | 1 | 1 | 1 | 1 | 有 | 6
方案3 | 2 | 1 | 1 | 1 | 1 | 2 | 无 | 8
方案4 | 3 | 1 | 1 | 1 | 2 | 1 | 有 | 9
方案5 | 1 | 2 | 1 | 1 | 2 | 1 | 无 | 9
方案6 | 2 | 1 | 1 | 1 | 2 | 2 | 无 | 9

**Comment by paderlol** [comment]
Dubbo Zookeeper注册中心 服务单向同步Nacos 基于**方案5**目前初步实现迁移功能。
