### ISSUE TITLE
zk -> nacos同步，节点下线报NPE

### ISSUE THREAD

**Issue by lkxiaolou** [nacos-group/nacos-sync#133]
![image](https://user-images.githubusercontent.com/6935924/72509850-5d92e280-3883-11ea-88b2-8ae396be4ea5.png)

**Comment by paderlol** [comment]
我拿的是上一层的data,这个null NPE没关系

**Comment by paderlol** [comment]
请确认下是不是别的问题导致的NPE,我暂时先关闭这个issue了,欢迎联系我
