### ISSUE TITLE
eureka集群配置问题

### ISSUE THREAD

**Issue by Heguoya** [nacos-group/nacos-sync#136]
配置集群模式，保存在数据后，格式出现问题，这个难道就我自己出现了？["\"http://10.19.*.*:6870/eureka\",\"http://10.19.*.*:6870/eureka\",\"http://10.19.*.*:6870/eureka/\""]

**Comment by paderlol** [comment]
嗯，目前eureka确实只支持一个节点

**Comment by paderlol** [comment]
因为eurekaclient 本身并没有做多节点集群的负载均衡，扩展性比较差，直接使用spring 的 clouddiscoveryclient 强制要求去注册服务，所以并没有采纳。不过eureka单节点做迁移的话应该还好，因为他毕竟不是像dubbo注册的是服务实例，注册都是应用实例

**Comment by Heguoya** [comment]
多谢，公司一个需求，正好使用到这个项目。



在 2020-03-19 22:58:45，"pader" <notifications@github.com> 写道：

因为eurekaclient 本身并没有做多节点集群的负载均衡，扩展性比较差，直接使用spring 的 clouddiscoveryclient 强制要求去注册服务，所以并没有采纳。不过eureka单节点做迁移的话应该还好，因为他毕竟不是像dubbo注册的是服务实例，注册都是应用实例

**Comment by paderlol** [comment]
客气。

**Comment by paderlol** [comment]
客气。
