### ISSUE TITLE
nacos-sync0.3.x对应nacos版本是多少

### ISSUE THREAD

**Issue by cdmaji** [nacos-group/nacos-sync#148]
nacos-sync0.3.x对应nacos版本是多少 测试最新版本nacos 1.2.1 同步并不成功(zk-->nacos)

**Comment by cdmaji** [comment]
closed by myself. cause by: nacos-sync0.3.x依赖nacos-client为1.0.4，使用nacos 1.2.1server，并不兼容，更换client version为1.2.1解决。避免后续同学踩坑。

**Comment by allen-kaiser-cai** [comment]
我这边用最新的nacos 1.3.0版本，也是无法同步成功(zk-->nacos)

**Comment by paderlol** [comment]
Dubbo吗？
