### ISSUE TITLE
Nacos-Sync是否支持Nacos集群之间的配置信息同步

### ISSUE THREAD

**Issue by junjie-tang99** [nacos-group/nacos-sync#156]
我们的服务在3个机房都会进行全量部署，同时每个机房都会部署1套Nacos集群。想确认下，Nacos-Sync是否支持Nacos集群之间的配置信息同步，不仅仅是服务信息的同步？

**Comment by paderlol** [comment]
是每个集群后面的数据库都是独立的吗？目前是没有集群之间的互相同步的，你指的的同步是服务信息同步，还是同步任务同步？如果是服务信息同步这个肯定不能集群和集群之间同步，因为这里涉及到心跳问题，如果是任务同步这个我不理解具体的意义是哪里？

**Comment by junjie-tang99** [comment]
是每个集群后面的数据库都是独立的吗？
答复：每个Nacos集群后面的数据库都是独立的

目前是没有集群之间的互相同步的，你指的的同步是服务信息同步，还是同步任务同步？
答复：我指的是Nacos中的配置信息同步。因为，在多机房的场景下，除了中间件的服务地址不同以外，大部分的应用配置信息都是一样的。所以，我们想实现的效果是，修改一个机房中的配置信息，可以将配置信息同步到其他机房的Nacos集群中。

**Comment by paderlol** [comment]
配置信息不支持同步，只支持注册中心，不过nacos本身支持配置信息导入的，可以自己通过程序互相API直接导入

**Comment by samandqq** [comment]
请教一下哈，这里的API导入是指批量导入，还是指openapi里面的‘发布配置API’（逐条导入）

**Comment by paderlol** [comment]
可以批量

**Comment by jerrychern** [comment]
@junjie-tang99 您好，你们三机房（记为A、B、C）部署了各自的nacos集群，使用nacos-sync同步，想请教三个问题：
1. nacos-sync在每个机房都部署了吗？同步方式是AB、AC、BC、BA、CA、CB 吗？
2. nacos-sync部署的是集群吗？如果是，有没有出现A机房服务下线之后，B机房显示服务还在？
3. nacos-sync页面你们做了用户名和密码吗？现在我们是直接打开页面就能配置。
