### ISSUE TITLE
使用eureka同步至nacos可以成功,但nacos同步至eureka却失败了

### ISSUE THREAD

**Issue by yueyuanyu** [nacos-group/nacos-sync#157]
使用eureka同步至nacos可以成功,但nacos同步至eureka不行,但是readme上介绍的是可以支持nacos
同步至eureka的.请问这是怎么回事

**Comment by paderlol** [comment]
Cloud吗？

**Comment by paderlol** [comment]
能提供下错误日志吗？

**Comment by paderlol** [comment]
这种很有可能是eureka版本导致的，传输的结构变化导致的，但是具体需要看错误日志

**Comment by yueyuanyu** [comment]
> 能提供下错误日志吗？

我们的eureka版本很低,sync控制台不报错呀 发出一个同步事件后就没输出任何有关这个任务的日志了

**Comment by paderlol** [comment]
Eureka server端报错了吗？

**Comment by paderlol** [comment]
还有你同步的方式，是从nacos新注册一个服务同步到Eureka，如果是eureka同步过来的服务，nacos是不会再同步了的，可以参考https://github.com/paderlol/nacos-sync-example 这是我写的几个例子

**Comment by yueyuanyu** [comment]
> 还有你同步的方式，是从nacos新注册一个服务同步到Eureka，如果是eureka同步过来的服务，nacos是不会再同步了的，可以参考https://github.com/paderlol/nacos-sync-example 这是我写的几个例子

你好 ,eureka端没有报错, nacos-sync端也只是发出一个同步任务后就没动静了  我们springcloud版本是E.是版本太低的原因吗  测试方式是直接注册到nacos上的服务同步到eureka 目前我们想要的效果是nacos和eureka双向同步实现平滑迁移至nacos 即线上所有服务从eureka同步至nacos, 以后的服务直接注册到nacos端, nacos端上线一个服务就同步至eureka上,同时,eureka上下线一个服务,最终全部迁移至nacos.实现平滑迁移.

**Comment by paderlol** [comment]
不应该你是不是填了组？

**Comment by paderlol** [comment]
nacos 添加同步任务不用填写组的

**Comment by yueyuanyu** [comment]
> 不应该你是不是填了组？

![image](https://user-images.githubusercontent.com/33542699/87130783-074cac80-c2c6-11ea-8b2e-1bcd42b79968.png)
queshi确实填了组

**Comment by yueyuanyu** [comment]
我试下不填组

**Comment by paderlol** [comment]
Nacos目前不支持组，只会在default下面寻找

**Comment by yueyuanyu** [comment]
> Nacos目前不支持组，只会在default下面寻找

原来如此 可以了 谢谢

**Comment by paderlol** [comment]
这个功能，我看下周末有时间就加上

**Comment by yueyuanyu** [comment]
> 这个功能，我看下周末有时间就加上

如果能支持nacos的nameSpace就好了 之前看有那个字段 尝试前端开放 发现没什么用,很尴尬
