### ISSUE TITLE
nacos sync双向同步咨询

### ISSUE THREAD

**Issue by tim1888** [nacos-group/nacos-sync#158]
@paderlol 
1、nacos sync双向同步：是指服务A的一个实例A1注册在Nacos，另一个实例A2注册在Zookeeper，这时候是可以分别由Nacos同步到Zookeeper、Zookeeper同步到Nacos，两边不会重复？

2、看到你去年5月份文章，说在规划0.40版本了，最近开发到什么进度了？
期待：同步数据一致性校验、支持 Eureka/Consul 和 Nacos 的双向同步

**Comment by paderlol** [comment]
1.第一个问题，不会重复，因为双向同步得时候在元数据里面做了打tag操作。
2. 第二个问题 eureka consul双向同步已经实现，双方数据一致性校验暂时没有做，由于个人工作原因没有及时开发，不好意思。另外consul同步暂时不支持多datacenter模式
