### ISSUE TITLE
优化 Nacos 向 Nacos 同步的方案

### ISSUE THREAD

**Issue by lexburner** [nacos-group/nacos-sync#167]
1. 目前 Nacos 向 Nacos 同步服务不支持填写 namespace，建议支持掉 namespace 的设置。
2. Nacos 向 Nacos 同步时有一个分组的框可以设置，但其实只支持留空，代表 DEFAULT_GROUP，会给用户带来困扰，建议去掉，或者采取其他优化方式。
3. 目前只支持单个服务同步，最好能够支持通配符的方式批量同步。

**Comment by gaoxiang9457** [comment]
1.特别需要同步时数据对比页面
2.特别需要同步结果界面
3.部署步骤复杂,启动脚本兼容性较差
4.测试\前端\后端\发布脚本作为4个maven子项目是为了显得代码多吗

**Comment by paderlol** [comment]
前面三点我觉得说的挺好的,第四点如果只是单纯对项目不满,我建议冷静下再来说,或者提出你觉得应该怎么样,纯粹的抨击没有任何意义,这是开源项目并不是利益项目,搭把手比吐槽更有意义不是吗？

**Comment by gaoxiang9457** [comment]
> 前面三点我觉得说的挺好的,第四点如果只是单纯对项目不满,我建议冷静下再来说,或者提出你觉得应该怎么样,纯粹的抨击没有任何意义,这是开源项目并不是利益项目,搭把手比吐槽更有意义不是吗？

可能是我使用感受不好,但我觉得你说得很对,你能帮忙调整一下结构吗

**Comment by HaojunRen** [comment]
不少Nacos关联项目的Committer也跟你一样，一开始是使用者，后面慢慢变成了贡献者，他们自身有公司自己的工作要做，牺牲很多宝贵的业余时间，甚至是国庆节等这样的法定节假日，无偿贡献
