### ISSUE TITLE
web控制台上删除同步任务，实际做了物理删除会导致该任务无法从内存中同步剔除掉

### ISSUE THREAD

**Issue by xiongshilin** [nacos-group/nacos-sync#168]
在web控制台上直接删除某个任务做了物理删除，会出现QuerySyncTaskTimer在下次执行时再也获取不到被删除的任务，内从中任务会一直存在除非重启服务

**Comment by paderlol** [comment]
哪个同步？

**Comment by xiongshilin** [comment]
QuerySyncTaskTimer 就是这个定时任务扫描数据库的同步任务时候，如果在控制台暂停任务后很快做一个删除，就有可能出现内存任务无法同步暂停删除掉。我们在部署测试环境时候遇到了。我们用的版本是0.3.9

**Comment by paderlol** [comment]
嗯，可能会有这个问题，我想下怎么修复下，因为你删除物理数据以后，定时任务找不到了，所以无法清理这个任务了
