### ISSUE TITLE
代码中serviceName使用默认gourpId导致配置Nacos至zk同步不成功

### ISSUE THREAD

**Issue by cdmaji** [nacos-group/nacos-sync#174]
NacosSyncToZookeeperServiceImpl中134行，      List<Instance> sourceInstances = sourceNamingService.getAllInstances(taskDO.getServiceName()); 调用getAllInstances API 没有传入GroupName，如果使用自定义的GroupName导致Nacos服务端/install/list接口无法获取instance，请问这个地方是一个bug还是有其他考虑呢？

**Comment by paderlol** [comment]
如果是默认 Nacos group就不需要填写，另外当前不支持自定义的Nacos group同步

**Comment by cdmaji** [comment]
另外，目前同样是nacos-->zk同步，namespaceId使用的是groupName，如果namespaceId和groupName不一致，同样导致去nacos获取不到instance（比如namespaceId:public groupName: DEFAULT_GROUP），这一块也暂时不支持吗？

**Comment by paderlol** [comment]
嗯，目前就支持默认空间的

**Comment by cdmaji** [comment]
好，谢谢
