### ISSUE TITLE
关于集群部署问题

### ISSUE THREAD

**Issue by cdmaji** [nacos-group/nacos-sync#177]
当前sync貌似不支持集群环境多节点部署，如果部署多节点，从效果上看(Nacos-->ZK为例)基本上是每个节点都是初始化同步&创建订阅，根据通知更新zk，或许从效果上看大部分情况下最终能在周期内达到一致，但是如果考虑复杂极端情况下(如多次短间隔内的修改，多节点之间订阅通知时序差异问题)，可能导致最终数据的不正确。其实，解决方法挺多，如在多个节点操作时增加一个带时序的互斥，即可做到。 这点请问后续有没有考虑加入？否则，单节点执行同步任务，在节点意外情况下，需要监控等后续运维快速定位并处理，否则可能对于服务调用来说可能导致大量报错。

**Comment by paderlol** [comment]
你是指的同一个数据库吗？如果是同一个数据库，应该只会有一个任务会执行

**Comment by cdmaji** [comment]
是同一个数据库，貌似跨进程之间不能保证只有一个任务执行吧，只能同一进程内通过finishedTaskMap保证只有一个任务执行吧。

**Comment by paderlol** [comment]
哦，明白你的意思了，你需要部署多实例sync来做注册中心同步？但是会有需求频繁变动服务上下线，所以出现ABA问题？我没有太理解这个点，能详细说下吗？

**Comment by cdmaji** [comment]
首先考虑到sync的可用性，采用多sync实例来做是最直接的，这是我们考虑多实例sync来做注册中心同步的目的；
然后，类似ABA问题，多节点执行A[]至B[]的同步更新，虽然最终能保证B[]的正确可用列表，但是很有可能是A[]-->B[]-->A[]--->B[]等的时序问题，虽然最终可以一致，但是中间不可用列表的时间将会和节点数成正比；并且zab本身是单leader，写性能本身就有局限，没有必要增加zk的写压力；并且，依赖于zk的watch事件，我们没有做事件merge，多次对于同一path的重复ABA操作会导致多次事件触发。
其实，问题本身就是多节点同时执行任务的时候带来的复杂度增加的问题，只要保证一个任务只执行一次既可。这样复杂度会降低很多。

**Comment by paderlol** [comment]
嗯，懂了，其实之前有考虑过引入zk锁来解决这个问题，但是当时一直在考虑是否额外引入zk的锁机制解决这个问题不太好，因为其他服务同样也存在这个问题，我在想可能去依赖Nacos本身来解决这个问题，在同步的同时去Nacos注册一个伪装服务，用来判断是否已经有节点在处理相关任务了，当节点不可靠时，转移至其他节点来注册这个服务，不过需要验证一下。

**Comment by paderlol** [comment]
因为这涉及到所有同步服务都建立相关机制，这样保证单个实例的保活机制

**Comment by paderlol** [comment]
这个问题我争取这两个星期解决掉，到时候发个版本

**Comment by cdmaji** [comment]
嗯，使用Nacos的naming注册一个伪服务，根据是否有Instance判断是否当前已经有在执行任务也是一种办法。但是个人觉得偏重了一些，因为：1、本业务特性决定只是一个互斥操作，不需要未抢到锁的线/进程阻塞在锁释放后重新开始竞争；2、Nacos目前版本机制需要通过http发送心跳来维持Instance，感觉此机制对于此业务不太适合（或许注册一个持久化节点要适合一点）；3、“锁”粒度问题，对于同步任务，在节点变更频繁下情况下，如果使用同一个“锁”，可能会有后续任务（Nacos订阅变更）长时间竞争不到的可能（如果上一次变更抖动很大），竞争比较激烈，可考虑将“锁”粒度放大，同一次变更（Nacos订阅变更）一把“锁”；
我之前的想法是，既然sync工具都依赖于Mysql，何不使用Mysql实现一把轻量级别的“锁”，实现同一批任务互斥操作即可，而且“锁”粒度足够细下，竞争不激烈，同样可以基于Mysql的持久化“锁”决定任务是否重跑或者丢弃等操纵。使用Mysql实现分布式互斥确实有点low，但是基于锁竞争，依赖程度等维度考虑本业务还是比较适合。以上是个人看法哈，期待2周后的版本。

**Comment by paderlol** [comment]
基于mysql的锁这个似乎可行，但我有一个问题就是死锁，当实例挂掉的时候需要考虑其他节点如何感知，定时更新一个时间戳来感知？

**Comment by cdmaji** [comment]
死锁对于这个业务来说，不致命。如果按照一次变更通知一个锁维度来设计，1次变更只有一个节点抢到锁，其他进程获取不到则结束。如果这个节点跑挂，锁的状态一直为running，可以使用补偿的线程来处理，如果这次锁后面有更近的锁时间戳，则放弃这个running状态的补偿操作（说明已有最新的变更，按照最新的完成最终一致即可），如果没有更近的锁时间戳，说明当前这个任务为最新的变更，那启动一个全量拉取的任务（和初始化一样）即可( 同样这个补偿任务也需要考虑多节点互斥问题，但是作为补偿任务主动发起比起变更被动触发要可控的多)。

**Comment by cdmaji** [comment]
一个节点挂点，其他节点快速接管这个属于HA范畴，按照二八原则，我觉得可以在这种情况下牺牲一部分实时性来保证大部分时候的可用性。

**Comment by paderlol** [comment]
你指的补偿是人工发现后干预？我没太明白你说的最新时间戳是指的什么？另外如果这样做，多实例的意义可能更多像一主多备，因为没有HA的情况下，大部分的任务更多跑在一个节点下，这个对很多企业来说也是不可接受的，他们可能没有你这种经常变动上下线的场景，只是考虑的是从原来的过渡到Nacos。他们对这个频繁变动带来得影响是能接受的，还有目前你的建议里面实际也有实时性的问题，全量重复的最终一致性至少没有需要人工干预，而且这个性能的损耗更多在于zk上，其实在eureka这种来说是没那么明显的。我们希望这个迁移工具在复杂度尽量低的情况下去做这些事情，它的核心作用毕竟不是作为双注册中心一直存在，不过mysql的方案我觉得可以讨论下，这个似乎复杂度不高，只需要解决如何比较方便的完成其他节点自动感知就好，比如A实例挂了，B的轮询能启动这些死锁的Job

**Comment by cdmaji** [comment]
确实如你说的，我之前想的可能更像主备的模式，但是如果做成真正的HA，还需考虑到任务的Balance等确实代价和复杂度高了一点，作为一个工具来说确实不太划算。另外，双注册中心不会一直存在，但是对于一些体量较大的公司来说，平缓迁移和双注册中心存在一定的时间和周期是完全可能的，并且在一些单元化(Zone)的架构体系内，实际上我们也可能希望通过sync来完成GZone的同步。Mysql这个方案，我在想想，确实在复杂度上和成本来说是比较可以接受的。

**Comment by paderlol** [comment]
好的感谢，我也想想，有想法我们可以碰下，你可以钉钉上加下我

**Comment by cdmaji** [comment]
好的，你钉钉号多少？我加下

**Comment by paderlol** [comment]
paderzhang356

**Comment by shalk** [comment]
这个问题现在修复或者有缓解么 @paderlol

**Comment by jerrychern** [comment]
@paderlol 大佬您好。集群部署我们遇到了奇怪的现象：
我们A机房和B机房都是使用nacos作为注册中心，再利用nacos-sync双向同步某个服务（Service1），当nacos-sync只有一个节点的时候，没有任何问题。但是当我们部署三节点的nacos-sync之后，就出现以下两种异常情况：
1. A机房中某个java应用（含3个服务）部署了6个实例，停掉其中一个实例之后，在nacos控制台看到，3个服务有的实例数是6个，有的是5个；
2. B机房还能看到A机房被停掉的那个节点实例信息，如下：
![image](https://user-images.githubusercontent.com/41419582/107167557-1d555380-69f4-11eb-9b72-af9acdce1c65.png)
3. 还有一个问题：跟集群没关系，nacos-sync的页面没有用户名和密码，这个后续可以加上吗？

BTW：我们nacos-sync三集群使用的是同一个数据，配置都是一样的，如下：

```xml
server.port=8081
server.servlet.context-path=/
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.datasource.url=jdbc:mysql://x.x.x.x:3306/nacos_sync?characterEncoding=utf8
spring.datasource.username=xxx
spring.datasource.password=xxxxxx
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
```
