### ISSUE TITLE
eureka版本对应问题

### ISSUE THREAD

**Issue by mgsgxmgs23** [nacos-group/nacos-sync#188]
请问nacosSync与eureka、nacos有版本对应吗？
比如nacosSync-0.4.1对应eureka什么版本？

**Comment by huanzui** [comment]
springcloud 版本Edgware.SR4 经测试是不行的，改nacosSync中springcloud 版本编译报错

**Comment by paderlol** [comment]
好的，我找个时间升级下，然后做个说明

**Comment by paderlol** [comment]
#230 Upgraded
