### ISSUE TITLE
nacos集群A到nacos集群B没找到批量同步

### ISSUE THREAD

**Issue by jerrychern** [nacos-group/nacos-sync#198]
想请教一下，我们目前用的nacos-sync版本是0.4.1，我们有两个机房，用的都是nacos集群（分别用A、B表示）做为注册中心，现在想把nacos集群A的注册中心信息同步到nacos集群B。
搭建了nacos-sync之后，需要一个服务一个服务到添加，请问批量同步上线了吗？如果上线了，怎么操作？以下是我们的图
![image](https://user-images.githubusercontent.com/41419582/103875169-10032b80-510d-11eb-9f43-bdc9b48c0382.png)
另外：该图的左上方显示的还是 nacos-sync 3.0，但是我们搭建的0.4.1，不知道是不是写错了😄😄。

新增同步中界面是：
![image](https://user-images.githubusercontent.com/41419582/103874940-c0bcfb00-510c-11eb-879c-40313bd80ab5.png)
该图中没有找到批量同步的操作。

麻烦指教一下，多谢啦

**Comment by paderlol** [comment]
目前没有批量接口，可能暂时只能自己添加。

**Comment by jerrychern** [comment]
> 目前没有批量接口，可能暂时只能自己添加。

神速啊，多谢啦～

**Comment by spurtAndy** [comment]
@paderlol 这个后续会加吗

**Comment by paderlol** [comment]
是nacos到nacos吗？还是zk到nacos

**Comment by spurtAndy** [comment]
@paderlol  我现在是做Eureka到Nacos的平滑过度，两者这间可以批量同步吗？

**Comment by paderlol** [comment]
没有批量，你可以调用api接口自己建立任务
