### ISSUE TITLE
3机房nacos集群之间如何使用sync同步？

### ISSUE THREAD

**Issue by jerrychern** [nacos-group/nacos-sync#203]
@paderlol 您好，想请教3个问题：
1. 我们现在有3个机房，每个机房都是nacos集群，请问如何使用nacos-sync进行nacos注册中心同步？我们之前是两个机房（比如是A机房和B机房），也都是nacos集群，我们只在A机房搭建了nacos-sync，进行两个机房的注册中心双向同步，现在3机房该如何搭建nacos-sync？
2. nacos-sync只能同步注册中心，是不是因为配置中心确实不应该同步，配置中心应该使用每个机房特有的配置，就算两个机房90%的配置都相同，也应该使用自己的配置？
3. 注册中心同步的时候，是不是只用同步provider，不用同步consumer。

**Comment by paderlol** [comment]
配置确实没有支持进行同步，因为这里存在一个覆盖优先级的问题，建议应该尽量的通过导入的方式进行配置，而且配置你的变动性不大，如果通过同步复杂度其实特别高

**Comment by jerrychern** [comment]
> 配置确实没有支持进行同步，因为这里存在一个覆盖优先级的问题，建议应该尽量的通过导入的方式进行配置，而且配置你的变动性不大，如果通过同步复杂度其实特别高

那第一个和第二个问题呢？也帮忙解答一下呗。

**Comment by paderlol** [comment]
如果想三中心都互相同步，那就需要配置AB AC  BC BA CA CB     就可以了，但是如果你想高可用就没每个机房放一个sync，使用单独的库，这样重复注册，Nacos本身会过滤掉

**Comment by sourirer** [comment]
> @paderlol 您好，想请教3个问题：
> 
> 1. 我们现在有3个机房，每个机房都是nacos集群，请问如何使用nacos-sync进行nacos注册中心同步？我们之前是两个机房（比如是A机房和B机房），也都是nacos集群，我们只在A机房搭建了nacos-sync，进行两个机房的注册中心双向同步，现在3机房该如何搭建nacos-sync？
> 2. nacos-sync只能同步注册中心，是不是因为配置中心确实不应该同步，配置中心应该使用每个机房特有的配置，就算两个机房90%的配置都相同，也应该使用自己的配置？
> 3. 注册中心同步的时候，是不是只用同步provider，不用同步consumer。

1，三中心同步按目前架构来说，应该只能部署多个nacos-sync来进行，不过你可以考虑根据具体场景，做中心化同步任务试试，中心化sync感知三个集群的数据，并将数据merge之后下发给每一个注册中心，类似这样的方案可以考虑一下。

2，配置中心不同步的原因有你说的那个原因，但是我想配置中心没有同步的主要原因是因为性价比太低，配置是一次操作，修改频率很低的事件，没有必要进行对应的同步，如果的确需要，参考注册中心的实现应该也是可以的；

3，consumer只有服务治理的价值，所以没有同步的必要。

**Comment by jerrychern** [comment]
> 如果想三中心都互相同步，那就需要配置AB AC BC BA CA CB 就可以了，但是如果你想高可用就没每个机房放一个sync，使用单独的库，这样重复注册，Nacos本身会过滤掉

多谢啦

**Comment by jerrychern** [comment]
> > @paderlol 您好，想请教3个问题：
> > 
> > 1. 我们现在有3个机房，每个机房都是nacos集群，请问如何使用nacos-sync进行nacos注册中心同步？我们之前是两个机房（比如是A机房和B机房），也都是nacos集群，我们只在A机房搭建了nacos-sync，进行两个机房的注册中心双向同步，现在3机房该如何搭建nacos-sync？
> > 2. nacos-sync只能同步注册中心，是不是因为配置中心确实不应该同步，配置中心应该使用每个机房特有的配置，就算两个机房90%的配置都相同，也应该使用自己的配置？
> > 3. 注册中心同步的时候，是不是只用同步provider，不用同步consumer。
> 
> 1，三中心同步按目前架构来说，应该只能部署多个nacos-sync来进行，不过你可以考虑根据具体场景，做中心化同步任务试试，中心化sync感知三个集群的数据，并将数据merge之后下发给每一个注册中心，类似这样的方案可以考虑一下。
> 
> 2，配置中心不同步的原因有你说的那个原因，但是我想配置中心没有同步的主要原因是因为性价比太低，配置是一次操作，修改频率很低的事件，没有必要进行对应的同步，如果的确需要，参考注册中心的实现应该也是可以的；
> 
> 3，consumer只有服务治理的价值，所以没有同步的必要。

收到 多谢回答

**Comment by jerrychern** [comment]
@paderlol @sourirer 两位大佬，我们现在遇到新的问题了。我们使用 nacos-sync 双向同步A机房和B机房的服务，有两个问题：
1. 有的服务在A机房下线之后，B机房的列表里还有，观察了30分钟，还是这样，请问这个问题怎么解决。
2. nacos-sync停了之后，B机房这个服务还在。
![image](https://user-images.githubusercontent.com/41419582/107140823-cef67500-695f-11eb-8d53-10a443d62b13.png)

3. nacos-sync界面没有用户名和密码，怎么加？

**Comment by fanyanming2016** [comment]
> 如果想三中心都互相同步，那就需要配置AB AC BC BA CA CB 就可以了，但是如果你想高可用就没每个机房放一个sync，使用单独的库，这样重复注册，Nacos本身会过滤掉

想问一下，如果是采用AB AC BC BA CA CB同步，会不会出现同步风暴问题，导致数据不一致？有没有什么解决方案

**Comment by paderlol** [comment]
不会的，Sync内部持有一个已同步实例的快照，并且每次同步的实例都有打标，防止循环和重复同步

**Comment by fanyanming2016** [comment]
> 不会的，Sync内部持有一个已同步实例的快照，并且每次同步的实例都有打标，防止循环和重复同步

相当于每个机房的sync组件都配置AB AC BC BA CA CB同步？如果是每个机房的sync组件只负责同步远端的nacos集群，不同sync组件内部的同步互相看不到的。这种场景会重复同步吗？
