### ISSUE TITLE
nacos-sync增加登录功能

### ISSUE THREAD

**Issue by jerrychern** [nacos-group/nacos-sync#216]
现在sync直接输入ip port 就可以查看同步任务，可以加一个登录功能吗？如果可以，我这边提交PR。

**Comment by jerrychern** [comment]
0.4.7版本已经实现

**Comment by lvhejin** [comment]
> 0.4.7版本已经实现

@jerrychern 你好，我们使用0.4.8版本，默认还是无登录功能，请问怎么设置登录功能？
