### ISSUE TITLE
sync task from eureka to nacos was failed 

### ISSUE THREAD

**Issue by zy-yiyun** [nacos-group/nacos-sync#222]
The following error is reported when sync task from eureka to nacos was failed ？
![image](https://user-images.githubusercontent.com/81305812/112403600-b0024580-8d49-11eb-94d6-26c91476b395.png)

![image](https://user-images.githubusercontent.com/81305812/112403658-c7d9c980-8d49-11eb-9c5e-b5ee6b9126be.png)

**Comment by paderlol** [comment]
已经升级了最新版本的Spring Cloud可以重新尝试下新版本
