### ISSUE TITLE
Eureka同步到Nacos一直不断消费

### ISSUE THREAD

**Issue by wuhj** [nacos-group/nacos-sync#223]
![image](https://user-images.githubusercontent.com/4392849/114333739-98192700-9b7b-11eb-9e7f-6c72ea7fd9bd.png)
这个服务已经注册到nacos上了，可是后台还是在一直不断进入SpecialSyncEventListener进行消费，不断地去注册Nacos服务。

**Comment by paderlol** [comment]
因为这个没有事件通知,所以用的轮询全量同步的方式,不然无法保证上线下线
