### ISSUE TITLE
nacos同步nacos任务缓存导致只能注册一次

### ISSUE THREAD

**Issue by niostack** [nacos-group/nacos-sync#224]
使用的最新版本：0.4.4
现象：同步任务启动后只有第一次会同步实例，当源服务节点下线再上线的时候不会再去同步了，看代码是走了sourceInstanceSnapshot这个缓存的逻辑，同一个任务id，同一个节点只会同步一次，是不是少了一个节点下线清缓存的逻辑？

**Comment by paderlol** [comment]
收到

**Comment by paderlol** [comment]
已修复 可以用下0.4.5
