### ISSUE TITLE
Nacos cannot sync to Eureka

### ISSUE THREAD

**Issue by MrZhangisGood** [nacos-group/nacos-sync#228]
hi dear developer,

I have a question.

nacos version2.0 and version1.4 are cannot sync to eureka. No anything error log.

when i use eureka sync to nacos, it can work.

Nacos Sync version is 0.4.5

**Comment by paderlol** [comment]
Eureka版本不兼容导致的，目前里面没支持太高版本

**Comment by MrZhangisGood** [comment]
> Eureka版本不兼容导致的，目前里面没支持太高版本

您好，我试了1.x版本和2.x版本的eureka，都是只能eureka可以同步数据给nacos，而nacos同步不了数据到eureka。

**Comment by paderlol** [comment]
报错了吗？

**Comment by paderlol** [comment]
你可以看下这个仓库下面的例子https://github.com/paderlol/nacos-sync-example

**Comment by MrZhangisGood** [comment]
> 报错了吗？

没有报错

**Comment by MrZhangisGood** [comment]
> 你可以看下这个仓库下面的例子https://github.com/paderlol/nacos-sync-example

我看这个链接里面的例子，Eureka 到 Nacos也是单向同步，不支持双向

**Comment by paderlol** [comment]
里面有例子,只是没有写Readme.我自己尝试了是没问题的
![image](https://user-images.githubusercontent.com/7919984/115655802-9b27ca80-a366-11eb-91d2-ef99820d3a56.png)
![image](https://user-images.githubusercontent.com/7919984/115655825-a3800580-a366-11eb-8b61-9b980bc31296.png)

**Comment by paderlol** [comment]
不要填写分组和namespace,因为不支持

**Comment by MrZhangisGood** [comment]
> 不要填写分组和namespace,因为不支持

去掉分组和namespace后，可以了，非常感谢。
