### ISSUE TITLE
Nacos-sync 对2.0版本的Nacos，无法同步数据

### ISSUE THREAD

**Issue by MrZhangisGood** [nacos-group/nacos-sync#229]
您好，使用Nacos-sync（0.4.5），对于2.0版本的Nacos，不能从nacos同步数据到nacos。

**Comment by paderlol** [comment]
可以自己先自己clone下源码，升级下maven的包进行升级client包，打包用下，我等周末才有时间处理

**Comment by MrZhangisGood** [comment]
> 可以自己先自己clone下源码，升级下maven的包进行升级client包，打包用下，我等周末才有时间处理

ok

**Comment by paderlol** [comment]
Upgraded #230
