### ISSUE TITLE
nacos-sync:0.4.6  依赖 nacos-client:2.0.1 找不到NetUtils

### ISSUE THREAD

**Issue by cuizhennan** [nacos-group/nacos-sync#236]
com.alibaba.nacos.client.naming.utils.NetUtils

nacos-sync/nacossync-worker/src/main/java/com/alibaba/nacossync/extension/sharding/AbstractServiceSharding.java:[5,45] 找不到符号

**Comment by paderlol** [comment]
你是看的源码？

**Comment by cuizhennan** [comment]
> 你是看的源码？

是的

**Comment by paderlol** [comment]
好的 不小心合错了一个重构分支的代码,我现在切回来.

**Comment by paderlol** [comment]
现在好了 实在不好意思.

**Comment by cuizhennan** [comment]
> 现在好了 实在不好意思.
