### ISSUE TITLE
eureka同步到nacos2.0报错

### ISSUE THREAD

**Issue by Kallen0** [nacos-group/nacos-sync#239]
![image](https://user-images.githubusercontent.com/10429166/122057958-b9b5b980-ce1d-11eb-91de-0c6657c5cca1.png)
获取不到application，推测是eureka版本不兼容导致的，将nacos-sync引用的cloud版本降低到Finchley.SR2/Greenwich.SR1依旧不行

**Comment by paderlol** [comment]
目前最新版本是可以的，当然eureka server也要最新版本，否则就需要用0.4.6以下的版本去适应了，或者自己通过源码重新打包吧
