### ISSUE TITLE
Eureka同步到nacos，instance覆盖问题

### ISSUE THREAD

**Issue by imsuperli** [nacos-group/nacos-sync#245]
使用场景为eureka同步到nacos，有三个instance，但是同步到nacos后，仅有一个instance，测试发现，后同步的instance会覆盖之前的instance，将nacos-sync中nacos-client由2.0.1改为1.1.4，可以解决此问题，貌似跟同一个长连接只能注册一个instance有关

**Comment by paderlol** [comment]
对，现在2.0的设计导致一个实例持有一个连接，所以没法多实例共享，后面有计划解决这个问题

**Comment by rsedgewick** [comment]
请教下nacos-client回退到哪个最高版本能解决此问题？是否会因为降低client版本引起其他问题？

**Comment by paderlol** [comment]
1.4.2吧

**Comment by paderlol** [comment]
https://github.com/nacos-group/nacos-sync/releases/tag/0.4.7-Beta
