### ISSUE TITLE
NacosSyncToNacosServiceImpl执行delete和sync方法时没有判断目标集群是否为最初的源集群

### ISSUE THREAD

**Issue by zrlw** [nacos-group/nacos-sync#249]
nacos注册中心很多场景下会覆盖实例的元数据，可能导致nacos sync打的sourceClusterId等标签丢失，为避免循环注册、误删源集群注册实例，有必要对NacosSyncToNacosServiceImpl的delete和sync方法在needSync为真之后做一下加强处理：
1. 执行sync处理时，查询源集群快照，如果没有就将instance的ip和port以及task配置的sourceClusterId保存到源集群快照；否则判断需要同步的instance在快照里登记的源集群是否和同步任务的目标集群相同，相同则忽略本次sync任务；
2. 执行delete处理时，查询源集群快照，如果需要同步的instance在快照里登记的源集群和删除同步任务的目标集群相同，则忽略本次delete任务。
 修订代码详见： #248

**Comment by zrlw** [comment]
采用多实例单库部署nacos sync时，各个sync实例启动的时间不能间隔太长，间隔越长，后面启动的sync拿到被nacos注册中心剔除sourceClusterId的元数据的可能性越大。
只有在同步任务里配置实例来源IP列表，才能彻底解决元数据丢失的情况，只是那样改动就很大了。

**Comment by paderlol** [comment]
不行 这种比之前出问题的几率更大一些,而且不能再使用多实例了, 使用多实例循环数据的几率会特别大,因为你不知道哪些数据是从外面同步过来的,你第一次同步的时候说不定已经有别的实例同步进来了

**Comment by paderlol** [comment]
还有你这个问题 其实本质应该是发生在你几个注册中心都接收了相同实例的注册,如果避免掉相同实例的注册 那么就应该不会出现这个元数据清除的问题了吧

**Comment by zrlw** [comment]
我们各个机房的dubbo服务只注册到本机房的nacos注册中心，不会向其他机房的注册中心进行注册，机房之间采用sync进行实例同步。
查询集群快照是仅当needSync返回true时才做的加强，也就是说只有sourceClusterId标签为空时才做快照，所以正常情况下多个sync实例出现循环数据的概率不会增大。
解决问题的根源在于查清nacos注册中心在什么场景下清理元数据，如果只是将健康状态改为false才清理，那么之前的修订应该就可以了，否则无论怎么加强，都有被击穿的可能。

**Comment by paderlol** [comment]
懂你的意思, 就是在现有基础上本地在进行一次校验,但是这个Map不受管控有点风险.
