### ISSUE TITLE
Swagger API is 404

### ISSUE THREAD

**Issue by huangyunbin** [nacos-group/nacos-sync#25]
Swagger API: http://127.0.0.1:8081/skywalker/swagger-ui.html#/  is 404
![image](https://user-images.githubusercontent.com/1046037/50961281-40099b00-1502-11e9-9e98-e4d0f82f84d0.png)

**Comment by wyp12** [comment]
由于系统名字变更,为了兼容2边,已经将context-path换成了/
访问地址改成: http://127.0.0.1:8081/swagger-ui.html#/ 

文档已更新#27

**Comment by lvhejin** [comment]
你好，我试了几个地址，都无法访问swagger-ui

![image](https://github.com/user-attachments/assets/be1153f4-a351-4e98-a667-60b34e7364dc)
