### ISSUE TITLE
大规模重启服务实例时，突然激增的sync同步实例任务会导致nacos注册中心崩溃

### ISSUE THREAD

**Issue by zrlw** [nacos-group/nacos-sync#252]
需要控制sync同步任务的发起节奏，对短时间内重复的同步任务进行合并处理。

**Comment by zrlw** [comment]
nacos sync定位是实时同步小量变动，因此大规模启停实例时，应当先停止nacos sync服务。
另外采用接口实例级别注册本身也有局限，不适合大规模应用场景，应该尽早过渡到服务注册级别。

**Comment by zrlw** [comment]
我们定制了一个版本：```https://github.com/zrlw/nacos-sync/tree/patch-mergeEvent```
合并了30秒内同一服务接口不同实例的事件通知，大大减少了事件处理的数量：我们每个接口平均有100多个实例，大规模重启时，合并后的事件通知数量会减少两个数量级。
我们还在定制的版本做了5分钟空闲兜底处理，如果5分钟没有事件，就做一次全量同步。
这些修订是我们和国内某H大厂交流之后做的，他们全球各注册中心之间的同步也对事件进行了合并，否则扛不住大规模变更。

**Comment by paderlol** [comment]
这个以前就有人做过了,但是需要改Nacos Server

**Comment by zrlw** [comment]
应该和nacos server无关。
我们每个taskID平均有100个instance，如果不合并事件，同时启动这100个instance时会产生100个事件，因为此时sourceInstanceSnapshot快照里都还没有东西，所以每个事件的sync方法会向nacos server发出100个registerInstance请求（因为source注册中心已经注册好了100个实例）），这样发给nacos server的请求数量会从100个变成1万个。

**Comment by paderlol** [comment]
我说你合并心跳发送，那等于是要改client发送心跳和Nacos接收心跳不是吗？

**Comment by paderlol** [comment]
还有你合并事件就是你可以容忍数据不实时，并且你的目的看起来更多不是在迁移，而是双注册中心

**Comment by zrlw** [comment]
1. 不是合并心跳，是合并注册请求，抓包发现大规模重启时，sync发起注册请求的数量比心跳数量高两个数量级。
2. 是用来作多注册中心，本中心应用优先访问本注册中心，异地中心不要求实时，最终一致即可。

**Comment by paderlol** [comment]
是因为互相收事件导致的，你这个解决方案在不要求一致性的情况下可以，靠rpc本身的负载来规避有些服务不可用的情况

**Comment by zrlw** [comment]
建议nacos sync搞个多注册中心的分支。
我们本来想直接去买多注册中心产品，但是大厂的注册中心和自己的产品捆绑得太紧，拿不出来单独销售，他们推荐我们试试nacos server + nacos sync，所以多注册中心这方面应该是有需求的，这样的需求和迁移存在很大差异，在一个分支下面搞可能相互影响。

**Comment by zrlw** [comment]
另外nacos的BeatReactor没有考虑同一个客户端同时注册同一实例，这么搞同一实例会搞出来多个心跳任务。
我们给nacos社区提交了一个fix：
https://github.com/alibaba/nacos/pull/6537

**Comment by paderlol** [comment]
同一客户端同时注册同一个实例,在什么场景下会出现？

**Comment by zrlw** [comment]
nacos sync收到nacos注册中心服务通知时，会从注册中心取出服务的全部实例，如果没有同步过（ConcurrentHashMap保存同步过的服务实例）就会发起注册。
假如同一类服务多个实例同时启动，比如有500个实例，注册中心几乎在同一时刻送给sync500个服务通知，sync没有对这些事件进行合并处理，此时ConcurrentHashMap还是空的，好比500个程序同时执行if (i==0) i++的操作，期望结果是1，但是实际结果比1大得多。

**Comment by paderlol** [comment]
所以会造成有两个心跳启动是吧,OK 这个等于是Sync接收事件会导致的特殊场景造成了会出现这个问题对吗？

**Comment by zrlw** [comment]
是的，一键启动应用的时候，如果实例数量庞大，就会遭遇这个问题，我提了个PR #267 ，应该能够减轻一些注册中心的负担。
