### ISSUE TITLE
Eureka<->Nacos服务同步问题

### ISSUE THREAD

**Issue by xyohn** [nacos-group/nacos-sync#262]
目前的需求是 希望能从eureka同步服务到nacos指定的namespace 也能从nacos指定的namespace同步服务到eureka（用于服务之间的迁移）
目前页面上，nacos-sync服务同步上，是支持在新建同步任务时填入命名空间id的 但是测试发现不生效
![image](https://user-images.githubusercontent.com/26292685/127129536-9d41acca-a68d-4595-93be-2c515fdce278.png)

如果不填命名空间id （相当于同步到public） 是没问题的 
clone了源码看了一下 代码层面可能有问题
1. NacosSyncToEurekaServiceImpl中 获取Nacos的NamingService和Eureka的NamingService时 第二个参数传入的是taskDO.getGroupName() ，但方法里 第二个参数应该是namespace

![image](https://user-images.githubusercontent.com/26292685/127129686-d060a746-8ee8-4848-b885-b07c2db20710.png)
![image](https://user-images.githubusercontent.com/26292685/127129685-2f144102-d73f-4e76-be93-9d19a3741d66.png)
2. EurekaSyncToNacosServiceImpl中 获取Nacos的NamingService和Eureka的NamingService namespace默认是传null

![image](https://user-images.githubusercontent.com/26292685/127129770-cd9aca24-61f3-4ec5-a8d1-cf2ff39f4ab3.png)

第一个问题..应该是个bug？ 
第二个问题..应该是设计如此？

**Comment by xyohn** [comment]
如果是bug我这边可以提个pr

**Comment by xyohn** [comment]
如果是bug 我这边提个pr

**Comment by paderlol** [comment]
可以拉取最新0.4.7-PRE进行使用了
