### ISSUE TITLE
0.4.7-PRE版本同步nacos 2.x注册中心时支持多实例么？

### ISSUE THREAD

**Issue by zrlw** [nacos-group/nacos-sync#269]
0.4.6版本不支持同步多实例的问题在0.4.7-PRE版本得到解决了?  请问测试使用的是nacos server 2.x的哪个版本？

**Comment by paderlol** [comment]
可以，我把客户端退回到1.4.2了，所以Nacos2.0可以支持了，但是如果用Nacos 2.0客户端就不行了

**Comment by paderlol** [comment]
2.0客户端需要等Nacos那边支持

**Comment by zrlw** [comment]
ok
