### ISSUE TITLE
nacos-sync 是否支持同一个集群的nacos不同namespace 进行服务信息的同步

### ISSUE THREAD

**Issue by zhangle910522** [nacos-group/nacos-sync#272]
如题，请问目前是否支持，不支持的话 后续是否会考虑改需求。谢谢

**Comment by paderlol** [comment]
自己建两个不同namespace的集群就行了

**Comment by zhangle910522** [comment]
> 自己建两个不同namespace的集群就行了

但是集群配置里面，新建集群 无法指定namespace，我这里说的是 同一个集群 多个 namespace 能否支持同步

**Comment by paderlol** [comment]
新版本里面有，我说了建两次同一个地址不同namespace的集群

**Comment by zhangle910522** [comment]
> 新版本里面有，我说了建两次同一个地址不同namespace的集群

![image](https://user-images.githubusercontent.com/28779854/131478852-419a46c6-1e8a-437f-aa9a-9c085c6bbae1.png)
这里并没有指定namespace的输入框，版本 0.4.6

**Comment by paderlol** [comment]
知道了,我周末找时间加下吧

**Comment by paderlol** [comment]
已经增加了,不过没太理解什么场景下你需要同一个集群内部进行不同namespace同步,按理来说注册到同一个空间就好了

**Comment by paderlol** [comment]
可以拉取最新0.4.7-PRE进行使用了

**Comment by zhangle910522** [comment]
> 可以拉取最新0.4.7-PRE进行使用了

可以了，但是我发现 暂停同步任务后，点击重新同步 无效了，而且我删除任务 新建任务也不行。后台日志无报错
服务反复关闭 重新注册 也无法同步了

**Comment by paderlol** [comment]
Fixed

**Comment by paderlol** [comment]
这个issue 关闭了,如果有其他问题麻烦提新的issue,然后有问题可以自己先定位一下.
