### ISSUE TITLE
nacos-nacos在暂停同步后再重新同步，目标集群无法再次获取同步信息

### ISSUE THREAD

**Issue by Davion2017** [nacos-group/nacos-sync#278]
nacos-server版本 2.0.3
nacos-sync版本 0.4.6
现象如标题描述
同步任务为从一个nacos集群同步到另一个nacos集群，在开启同步后，两个集群的信息能互通，nacos-sync界面暂停同步后再点击重新同步，源集群的服务信息就无法同步到目标集群了

**Comment by paderlol** [comment]
#274 已经修复了，使用0.4.7-pre版本

**Comment by Davion2017** [comment]
好的，谢谢
