### ISSUE TITLE
nacos当作配置中心使用不同中心数据同步

### ISSUE THREAD

**Issue by penghuazhou** [nacos-group/nacos-sync#287]
nacos-sync不支持配置中心各数据中心数据的同步吗？我不是把nacos当作服务发现产品来用的，当作配置中心来用，没有服务名和分组的概念。
![image](https://user-images.githubusercontent.com/13001038/150977783-5edad6f1-e7a2-43b5-9408-682967e9f083.png)

**Comment by jerrychern** [comment]
nacos-sync不支持配置中心同步，目前只支持注册中心。

**Comment by penghuazhou** [comment]
谢谢
