### ISSUE TITLE
eureka将服务同步到nacos时候，nacos-sync服务报java.lang.IllegalArgumentException: Malformed serviceUrl: 192.168.111.208:8761错误

### ISSUE THREAD

**Issue by dnrlxd** [nacos-group/nacos-sync#308]
nacos-sync版本是最新版本的nacos-sync-0.4.8，nacos-server使用的是nacos-server-1.4.1，eureka使用的是Hoxton.SR1版本。
eureka下有个服务amc-datalink-server，现在想将这个服务同步到nacos上，也是按照nacos官网的操作去操作的，具体网址为：
https://nacos.io/zh-cn/docs/nacos-sync-use.html。具体的操作和服务列表附件图片都有说明。主要报的错是
java.lang.IllegalArgumentException: Malformed serviceUrl: 192.168.111.208:8761
	at com.netflix.discovery.shared.resolver.DefaultEndpoint.<init>(DefaultEndpoint.java:45)。
AbstractServerHolderImpl.createServer时候使用的是具体EurekaServerHolder的createServer方法，跟踪nacosSync服务的源码可以知道
DefaultEndedPoint构建Url时候需要加上协议名，不能直接使用ip+port需要加上协议名，但是新增eureka服务的时候并没有明确要加上http://，二期官网实例只有zk的示例并无eureka的示例，这个可能是eureka的问题，但是咱们注册eureka服务的时候可以默认将http://带上啊。就是数据库cluster表的针对cluster_type为EUREKA的connect_list字段可以带上http://吧。

![具体报错代码定位](https://user-images.githubusercontent.com/55651759/190051241-885bc06b-abf9-438b-bb9f-7eacea6ad692.png)
![nacosSync服务报错](https://user-images.githubusercontent.com/55651759/190051452-8543ec57-6a80-46b9-b503-82b8510f1663.png)
![nacosSync服务同步](https://user-images.githubusercontent.com/55651759/190051486-9f46d207-2aa8-4baf-8ce5-1b9581b90d2b.png)
![nacosSync集群配置](https://user-images.githubusercontent.com/55651759/190051493-c4754fe5-786e-4b83-8876-b4a576faf1e4.png)

**Comment by paderlol** [comment]
Fixed

**Comment by dnrlxd** [comment]
good
