### ISSUE TITLE
Are there any plans to allow the Nacos-Sync project to run in Docker?

### ISSUE THREAD

**Issue by hereTac** [nacos-group/nacos-sync#313]
没有找到合适的讨论版块，所以发布信息在这里。 @paderlol 以及看到你的个人仓库存在该项目，https://github.com/paderlol/nacos-sync-docker 可以提供一些关于 nacos-sync docker 化的信息以及计划吗？

**Comment by lestchun** [comment]
自己在nacossync-distribution 新建个Dockerfile 然后自己build 不就好了么
```/bin/sh
FROM anapsix/alpine-java:8_server-jre_unlimited

ADD  ./target/nacosSync.0.4.7.tar.gz /

CMD ["/nacosSync/bin/startup.sh","start"]

```

**Comment by hereTac** [comment]
谢谢建议。（目前 nacos-sync 0.4.8 暂时对 nacos 2.1.1 的同步支持有些问题，暂不选择使用 nacos-sync 作为解决方案）
