### ISSUE TITLE
当源节点数据为空的,nacos-sync会删除目标节点上的所有实例信息

### ISSUE THREAD

**Issue by dragonTalon** [nacos-group/nacos-sync#350]
当源节点数据为空的,nacos-sync会删除目标节点上的所有实例信息
--------

 private void processDeRegisterInstances(TaskDO taskDO, NamingService destNamingService) throws NacosException {
        //如果此时sourceInstance中的实例为空，证明此时实例下线或实例不存在
        List<Instance> destInstances = destNamingService.getAllInstances(taskDO.getServiceName(),
                getGroupNameOrDefault(taskDO.getGroupName()), new ArrayList<>(), false);
        // 如果目标集群中的数据实例也为空了，则测试无需操作
        if (CollectionUtils.isEmpty(destInstances)) {
            return;
        }
        deRegisterFilter(destInstances, taskDO.getSourceClusterId());
        if (CollectionUtils.isNotEmpty(destInstances)) {
            //逐个执行反注册,拿出一个实例即可, 需要处理redo，否则会被重新注册上来
            for (Instance destInstance : destInstances) {
                destNamingService.deregisterInstance(taskDO.getServiceName(),
                        getGroupNameOrDefault(taskDO.getGroupName()), destInstance);
            }
        }
    }

com.alibaba.nacossync.extension.impl.NacosSyncToNacosServiceImpl#deRegisterFilter

    private void deRegisterFilter(List<Instance> destInstances, String sourceClusterId) {
        List<Instance> newDestInstance = new ArrayList<>();
        for (Instance destInstance : destInstances) {
            Map<String, String> metadata = destInstance.getMetadata();
            String destSourceClusterId = metadata.get(SkyWalkerConstants.SOURCE_CLUSTERID_KEY);
            if (needDeregister(destSourceClusterId, sourceClusterId)) {
                // 需要执行反注册
                newDestInstance.add(destInstance);
            }
        }
        destInstances = newDestInstance;
    }

问题在于对destInstances列表的更新方式。在Java中，方法参数是按值传递的。这意味着当你传递一个对象到方法中时，实际上传递的是对象引用的副本。因此，如果你在方法内部改变了这个引用指向的对象（例如，将其指向一个新的对象），这个改变不会影响到原始的对象引用。
在你的代码中，destInstances = newDestInstance;这一行只是改变了destInstances引用在方法内部的指向，而不会改变方法外部传入的destInstances列表对象。这意味着，尽管你筛选出了需要反注册的实例，但这个改变不会反映到方法调用者那里。

**Comment by luoxiner** [comment]
it seems like a bug, i will try to fix it later

**Comment by dragonTalon** [comment]
> it seems like a bug, i will try to fix it later

my fix two issue for 350 and 346 in  https://github.com/nacos-group/nacos-sync/pull/347

**Comment by luoxiner** [comment]
Thanks to your contributes, i will try to review it later.

**Comment by paderlol** [comment]
merged #347
