### ISSUE TITLE
0.5.0 版本SkyWalkerCacheServices.java里面的operationId字段的判断应该是代码写错了吧

### ISSUE THREAD

**Issue by MajorHe1** [nacos-group/nacos-sync#359]
![企业微信截图_171827998873](https://github.com/nacos-group/nacos-sync/assets/53824889/4692e9e4-7f0d-4b91-8c2f-fe4bc361fd9c)

isEmpty和 hasLength 明显语义不一致

**Comment by luoxiner** [comment]
It seems there was a mistake. Thank you for your contribution.
