### ISSUE TITLE
运行中遇到一些问题的汇总

### ISSUE THREAD

**Issue by nanamikon** [nacos-group/nacos-sync#5]
版本：
     最后一个commit 是 6bc3057

运行期间问题
1、程序中context已经改为nacossync， 但是前端还是用skywalker， 这样页面会出现404
2、SyncService这个接口已经定义了， 但是缺少一个地方在SyncManagerService中通过register方法来注册
3、目前最新版的nacos sdk， 是无法同步集群或者服务具体信息的，  这些是不是应该在nacos-sync做， 还是通过后台界面手动去做

**Comment by wyp12** [comment]
@loadchange  帮忙看看第一个问题:
1、程序中context已经改为nacossync， 但是前端还是用skywalker， 这样页面会出现404

**Comment by loadchange** [comment]
目前还有哪些地方使用了`skywalker` ？ 我刚刚检查了一下没有发现。 @wyp12

**Comment by wyp12** [comment]
![image](https://user-images.githubusercontent.com/4252147/49775733-122f0c00-fd34-11e8-8554-a104cdd6c37e.png)
@loadchange  请求数据的时候还有

**Comment by wyp12** [comment]
搞定
