### ISSUE TITLE
zk连接不上,会一直刷异常

### ISSUE THREAD

**Issue by wyp12** [nacos-group/nacos-sync#53]
![image](https://user-images.githubusercontent.com/4252147/51231155-78472880-199d-11e9-9eca-48bcdda591da.png)
新增加一个zk->nacos任务,如果zk集群连接不上,会打异常,将任务删除,也一直打

**Comment by paderlol** [comment]
* zk client 连接失败每隔一秒进行自动重连,删除任务和删除集群都不会对zk当前可能client进行移除,这是为了防止移除client造成其他task失败的情况.
* 目前改造成zk client 默认获取所有连接地址进行连接,来保证活性,然后重试间隔从原来1s改成3s
