### ISSUE TITLE
如何制定namespace??

### ISSUE THREAD

**Issue by xingtaoshi** [nacos-group/nacos-sync#60]
debug display nameSpace is null  

com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:81  - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=10, taskId=3475b1b5c930dfe1f4f19001155c7e87, sourceClusterId=8afc6b7d4758bc2bcdaa93ad2017a304, destClusterId=d0cb5c71a5576c5839ba6f341c90b84c, serviceName=ndev-sync, version=0, groupName=ndev, **nameSpace=null**, taskStatus=SYNC, workerIp=192.168.100.50, operationId=1a869552-842d-42da-9f03-c2bb39cf8a36)

**Comment by paderlol** [comment]
目前没有把命名空间放出来，后面会考虑放出来的


| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

在2019年01月24日 18:09，xingtaoshi 写道：

debug display nameSpace is null

com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:81 - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=10, taskId=3475b1b5c930dfe1f4f19001155c7e87, sourceClusterId=8afc6b7d4758bc2bcdaa93ad2017a304, destClusterId=d0cb5c71a5576c5839ba6f341c90b84c, serviceName=ndev-sync, version=0, groupName=ndev, nameSpace=null, taskStatus=SYNC, workerIp=192.168.100.50, operationId=1a869552-842d-42da-9f03-c2bb39cf8a36)

**Comment by paderlol** [comment]
目前Nacos支持namespace
