### ISSUE TITLE
nacos-sync log

### ISSUE THREAD

**Issue by morisenmen** [nacos-group/nacos-sync#69]
when a sync task run,I get this log:[从数据库中查询到一个删除任务，发出一个同步事件:...],and noting else.The task is done,or failed,or running.I do not know anything.Should we get more infomation when the sync task started.

**Comment by wyp12** [comment]
由于数据的同步,依赖于每个产品的客户端,
这些都是异步的操作,无法从返回中得知背后任务执行的真实情况
需要用户操作任务之后,自己去目标集群检查数据情况
